FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

copy . ./

run dir -l -s

WORKDIR ./src


run dir -l -s

COPY "Shopping/Shopping.Client/Shopping.Client.csproj" "Shopping.Client/"
RUN dotnet restore Shopping/Shopping.Client/Shopping.Client.csproj"

COPY . . 

RUN dotnet publish -c release -o out

FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /app

EXPOSE 80

COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "Shopping.Client.dll"]
