FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

RUN dotnet --version

WORKDIR /app


RUN pwd

run dir -r

run dir .

copy . ./

workdir shopping.client

dir dir -r

RUN pwd

run cd ..

RUN pwd

run dir -r
