version: '3.4'

services:
  shoppingdb:
    image: mongo

  shopping.client:
    image: ${DOCKER_REGISTRY-}shoppingclient
    build:
      context: .
      dockerfile: Shopping\Shopping.Client\Dockerfile

  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping/Shopping.API/Dockerfile

volumes:
  mongo_data:
